"""Physically motivated synthetic star clusters.

WHY THIS EXISTS
---------------
Drawing positions from a smooth King or EFF profile with Poisson noise is the
wrong generative model for a young cluster, and using it to validate a radial-profile
fit begs the question: it bakes in exactly the smoothness the fit assumes.

Young clusters are **not** smooth. They inherit fractal substructure from their natal
molecular clouds and retain it for several crossing times (Goodwin & Whitworth 2004,
A&A 413, 929, `2004A&A...413..929G`; Allison et al. 2010, MNRAS 407, 1098). Star
counts on real young regions give fractal dimensions well below the `D = 3` of a
uniform sphere.

:func:`fractal_cluster` implements the Goodwin & Whitworth box-fractal construction —
the same algorithm McLuster uses (Küpper et al. 2011, MNRAS 417, 2300,
`2011MNRAS.417.2300K`) — so substructured test data is generated by a citable,
standard method rather than by an ad-hoc sprinkling of Gaussian clumps.

STILL THE STANDARD, DESPITE THE DATES
-------------------------------------
Both references predate Gaia, which is a fair thing to be suspicious of. They have
not been superseded. Amiri et al. 2026 (`arXiv:2606.04509`, June 2026), from the
McLuster lineage group: *"Implementation of the initial condition is done using the
most updated version of the code McLuster … Initial fractal substructures were
implemented using the method described in Goodwin and Whitworth [2004] … we
investigated two extreme values: D = 3.0, which results in no substructure, and
D = 1.6, which results in a cluster with the maximum degree of fractality."* Same
prescription, same two limits used here. Kamlah et al. 2022 is often cited as
"updated McLuster" but scopes itself to *stellar evolution* recipes; the spatial
prescription is unchanged since 2011.

The acknowledged limitation is Torniamenti et al. 2022 (`2022MNRAS.510.2097T`):
fractal ICs *"do not guarantee that all the relevant characteristics of the actual
primordial conditions of star clusters are correctly captured"*. The upgrade path is
hydro-derived initial conditions (Ballone et al. 2020/2021), which measure `D = 1.0–1.8`
— *more* substructured than typical fractal ICs.

WHAT THIS DELIBERATELY DOES NOT DO
----------------------------------
No Gaia error model, no selection function, no photometry. Those belong to the other
standard — Hunt et al. 2025/2026 (`2025A&A...699A.273H`, `2026A&A...706A.341H`) and the
`ocelot` package, which inject mock clusters into real DR3 with the Cantat-Gaudin et al.
(2023) selection function and error "twin"-resampling.

The two standards do not overlap, and that is checkable: ``ocelot``'s distribution models
are King62, King64 and Plummer only, and Hunt et al. state outright that tidal tails and
coronae *"are not included by King profiles … we do not include them in our cluster
simulations"*. So the Gaia-aware generator is smooth, and the substructured generator has
no Gaia layer. **Combining them is an open niche, not a solved problem** — worth knowing
before assuming this module is behind the state of the art rather than orthogonal to it.

See ``docs/design-notes/synthetic_validation_baseline.md`` for the full adjudication.

WHAT IT IS FOR
--------------
Validation, not science. A profile fit that recovers its parameters from smooth
Poisson data but not from fractal data of the same radial profile is telling you
about the estimator, not about the cluster — and that distinction is the point.
"""

from __future__ import annotations

import numpy as np

__all__ = ["fractal_cluster", "radial_profile_of"]


def fractal_cluster(
    n_stars: int,
    *,
    fractal_dimension: float = 1.6,
    radius: float = 1.0,
    rng: np.random.Generator | int | None = None,
    max_levels: int = 12,
    noise: float = 0.0,
):
    r"""Generate a box-fractal star cluster (Goodwin & Whitworth 2004).

    The construction: start from a parent at the centre of a cube and divide it
    into eight sub-cubes. Each child matures with probability
    :math:`2^{\,D-3}`, so :math:`D = 3` fills the cube uniformly and smaller `D`
    leaves progressively more substructure. Mature children become parents and the
    division repeats. Positions are jittered at each level, then the final
    generation is pruned to a sphere and subsampled to `n_stars`.

    Parameters
    ----------
    n_stars : int
        Number of stars to return.
    fractal_dimension : float, default 1.6
        `D` in the construction above; must satisfy ``0 < D <= 3``. Values of
        1.6 correspond to the substructured regions studied by Goodwin &
        Whitworth; ``D = 3`` gives a uniform sphere and is the natural null.
    radius : float
        Radius of the bounding sphere, in whatever unit the caller wants.
    noise : float, default 0.0
        Extra Gaussian jitter per level, as a fraction of that level's cube size.
        **Leave this at zero unless you know why you want it.** It biases the
        radial profile: the jitter displaces each block *coherently* with its
        descendants, and blocks that move inward pile up where they meet at the
        centre. Measured on the ``D = 3`` case, where the answer must be a uniform
        ball, the innermost shells come out over-dense by

            noise   0.00   0.05   0.10   0.20
            excess  1.10   1.17   1.35   1.80

        (peak over the four innermost shells of 20000 stars; the 1.10 at zero
        noise is the shot noise of a ~20-star bin, 1.6 sigma, not a bias). So the
        G&W prescription's own jitter can manufacture a factor-1.8 central cusp
        out of a distribution that has none. It is not needed here: the
        cubic lattice is erased exactly by spreading each star inside its own
        final cell (see the implementation), which introduces no such bias.

    Returns
    -------
    ndarray, shape (n_stars, 3)
        Positions inside a sphere of `radius`, centred on the origin.

    Notes
    -----
    This generates **structure**, not a specific radial profile. Use
    :func:`radial_profile_of` to measure what profile a realization actually has,
    or rescale radii to impose one while keeping the angular substructure.

    Examples
    --------
    >>> pos = fractal_cluster(500, fractal_dimension=3.0, rng=0)
    >>> pos.shape
    (500, 3)
    >>> bool(np.all(np.linalg.norm(pos, axis=1) <= 1.0 + 1e-9))
    True
    """
    if not 0.0 < fractal_dimension <= 3.0:
        raise ValueError("fractal_dimension must lie in (0, 3].")
    if n_stars < 1:
        raise ValueError("n_stars must be positive.")
    rng = np.random.default_rng(rng)

    survival = 2.0 ** (fractal_dimension - 3.0)
    points = np.zeros((1, 3), dtype=float)
    size = 1.0

    for _ in range(max_levels):
        size *= 0.5
        # eight children per parent, at the sub-cube centres
        offsets = np.array(
            [[i, j, k] for i in (-1, 1) for j in (-1, 1) for k in (-1, 1)], dtype=float
        ) * (size * 0.5)
        children = (points[:, None, :] + offsets[None, :, :]).reshape(-1, 3)
        keep = rng.random(children.shape[0]) < survival
        children = children[keep]
        if children.shape[0] == 0:
            # The fractal died out; retry the level from the surviving parents.
            size *= 2.0
            continue
        children += rng.normal(0.0, noise * size, children.shape)
        points = children
        if points.shape[0] >= 8 * n_stars:
            break

    # Spread each star uniformly inside its own final cell. Without this the last
    # generation sits on a regular lattice: below the cell size the density is a
    # comb of delta functions, and because a projection collapses every z-layer
    # onto the same xy lattice the artefact survives projection and shows up as a
    # spurious central spike in any finely binned radial profile.
    points = points + rng.uniform(-0.5 * size, 0.5 * size, points.shape)

    # The construction fills a CUBE of half-width 0.5 (plus jitter). Prune to its
    # inscribed sphere and rescale to unit radius -- pruning at radius 1.0 would
    # remove nothing, silently returning a cube and giving every radial statistic
    # a corner-shaped outer edge.
    points = points[np.linalg.norm(points, axis=1) <= 0.5] * 2.0
    while points.shape[0] < n_stars:
        # Top up from a fresh realization rather than sampling with replacement,
        # which would place coincident stars and read as infinite density.
        extra = fractal_cluster(
            n_stars - points.shape[0],
            fractal_dimension=fractal_dimension,
            radius=1.0,
            rng=rng,
            max_levels=max_levels,
            noise=noise,
        )
        points = np.vstack([points, extra])
    idx = rng.choice(points.shape[0], size=n_stars, replace=False)
    return points[idx] * radius


def radial_profile_of(positions, *, bins=20, project=True):
    """Measure the radial surface (or volume) density of a realization.

    Parameters
    ----------
    positions : ndarray, shape (n, 3)
    project : bool, default True
        Project onto the sky plane (drop the third axis) and return a **surface**
        density, which is what the profile fits model. Otherwise return a volume
        density.

    Returns
    -------
    (centres, density) : tuple of ndarray
    """
    pos = np.asarray(positions, dtype=float)
    r = np.linalg.norm(pos[:, :2] if project else pos, axis=1)
    edges = np.linspace(0.0, r.max(), int(bins) + 1)
    counts, _ = np.histogram(r, bins=edges)
    if project:
        area = np.pi * (edges[1:] ** 2 - edges[:-1] ** 2)
    else:
        area = (4.0 / 3.0) * np.pi * (edges[1:] ** 3 - edges[:-1] ** 3)
    return 0.5 * (edges[1:] + edges[:-1]), counts / area
